### ISSUE TITLE
Unable to build latest logspout image with this module

### ISSUE THREAD

**Issue by DavidJBianco** [moovel/logspout-kinesis#4]
I'm trying to build a custom logspout image with your Kinesis module in it.  I cloned your repo and built against the Dockerfile, but I get an error from the build:

    (35/36) Installing python2 (2.7.13-r0)
    (36/36) Installing mercurial (4.0.1-r0)
    Executing busybox-1.25.1-r0.trigger
    OK: 406 MiB in 46 packages
    package github.com/moovel/logspout-kinesis: found packages logspoutkinesis (logspoutkinesis.go) and main (modules.go) in /go/src/github.com/moovel/logspout-kinesis
    The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 1

I think it's confused because _modules.go_ references the github repo in such a way that it really expects only a single _*.go_ file to be in the directory, which should be the kinesis module itself. 

I forked your repo and moved _logspoutkinesis.go_ into a newly-created _adapters/kinesis_ directory as _adapters/kinesis/kinesis.go_, and referenced in my modules.go as:

	_ "github.com/DavidJBianco/logspout-kinesis/adapters/kinesis"

I also ended up not needing most of the other files in the repo (_build.sh_, _modules.go_, etc), FYI.

This builds correctly, and the image works well (thank you!).  Would you consider moving the logspoutkinesis.go file out of the main directory and into a subdir, similar to the above?

**Comment by sbuettner** [comment]
I think this issue is now resolved by merging your PR #5 right?

**Comment by DavidJBianco** [comment]
Correct, thank you!

**Comment by sbuettner** [comment]
Thanks for your contributions.
